import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FrontEnd challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to FrontEnd challenge</h1>

        <p className={styles.description}>good luck</p>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/amirahmadd/behtarino-challenge"
          target="_blank"
          rel="noopener noreferrer"
        >
          github repo
        </a>
      </footer>
    </div>
  );
}
